**Question 1**


Question 1a

In [2]:
# Creating a function to import an XML file
import xml.etree.ElementTree as ET

#parse the xml document
xmlfile = 'NorthWind.xml'

def import_xml_file(xmlfile):
    try:
        xmldata = open(xmlfile, 'r')
        xmltree = ET.fromstring(xmldata.read())
        return xmltree
    except FileNotFoundError:
        print(f"Could not open the file:".format(xmlfile))
    except IOError:
        print(f"Could not read from the file:".format(xmlfile))
    finally:
        xmldata.close()
    return None


# Call the import_xml_file function to load the XML file
xml_data = import_xml_file(xmlfile)

if xml_data is not None:
    # You can now work with the 'xml_data' variable, which contains the XML tree.
    # For example, you can access elements and attributes using xml_data.findall(), xml_data.find(), etc.
    print("XML file successfully imported.")
else:
    print("XML file import failed.")
    

XML file successfully imported.


Question 2b

In [8]:
#CustomerID, OrderID, ShipCity, ShipCountry

parsed_xml =[]
for i in range(10,20,3) :
    product = xml_data.find(f".//Order[{i}]")
    CustomerID = product.find('CustomerID').text
    #OrderID = product.find('OrderID').text
    ShipCity = product.find('ShipCity').text
    ShipCountry = product.find('ShipCountry').text
    
    results =('CustomerID:{}\tShipCity:{}\tShipCountry:{}'.format(CustomerID,ShipCity,ShipCountry))
    parsed_xml.append(results)
    
    
    print('CustomerID:{}\tShipCity:{}\tShipCountry:{}'.format(CustomerID,ShipCity,ShipCountry))

CustomerID:HILAA	ShipCity:San Cristóbal	ShipCountry:Venezuela
CustomerID:OTTIK	ShipCity:Köln	ShipCountry:Germany
CustomerID:ERNSH	ShipCity:Graz	ShipCountry:Austria
CustomerID:WARTH	ShipCity:Oulu	ShipCountry:Finland


Question 1c

In [66]:
import xml.etree.ElementTree as ET
import csv

# Function to import an XML file (similar to what we've discussed before)
def import_xml_file(xml_file_path):
    try:
        xmldata = open(xml_file_path, 'r')
        xmltree = ET.fromstring(xmldata.read())
        return xmltree
    except FileNotFoundError:
        print(f"Could not open the file: {xml_file_path}")
    except IOError:
        print(f"Could not read from the file: {xml_file_path}")
    finally:
        xmldata.close()
    return None

# Function to extract customer data and save it to a CSV file
def extract_customers_to_csv(xml_tree, csv_file_path):
    if xml_tree is not None:
        # Open the CSV file for writing
        with open(csv_file_path, 'w', newline='') as csvfile:
            csvwriter = csv.writer(csvfile)

            # Write the header row (column names)
            header = ['CustomerID', 'ShipCountry', 'ShipCity']
            csvwriter.writerow(header)

            # Iterate through 'entry' elements to extract and write data
            for customer in xml_tree.find("Customers").findall("Customer"):
                customer_data = {
                    'CustomerID': customer.get('CustomerID'),
                    'ShipCountry': customer.find('CompanyName').text,
                    'ShipCity': customer.find('ContactName').text,
                    #'PostalCode': customer.find('PostalCode').text,
                }

                # Check if the customer has ID 5 before writing to the CSV
                if customer.find('CountryID') == 5:
                    csvwriter.writerow([customer_data[field] for field in header])

        print(f"Customer data from ID 5 successfully exported to '{csv_file_path}'")
    else:
        print("XML file import failed.")

# XML file path
xmlfile = 'NorthWind.xml'  

# CSV file path
csvfile = 'customers.csv'  # Specify the output CSV file path

# Import the XML file
xml_data = import_xml_file(xmlfile)

# Extract and write customer data to a CSV file
extract_customers_to_csv(xml_data, csvfile)


Customer data from ID 5 successfully exported to 'customers.csv'


#### Question 2


Question 2a


In [39]:
import numpy as np

# Create an ndarray with even numbers between 1000 and 8998
array_a = np.arange(1000, 8999, 2)

# Reshape the array to have 8 layers, 50 rows, and 10 columns
reshaped_array_a = array_a.reshape(8, 50, 10)

# Print the result
print(reshaped_array_a)


[[[1000 1002 1004 ... 1014 1016 1018]
  [1020 1022 1024 ... 1034 1036 1038]
  [1040 1042 1044 ... 1054 1056 1058]
  ...
  [1940 1942 1944 ... 1954 1956 1958]
  [1960 1962 1964 ... 1974 1976 1978]
  [1980 1982 1984 ... 1994 1996 1998]]

 [[2000 2002 2004 ... 2014 2016 2018]
  [2020 2022 2024 ... 2034 2036 2038]
  [2040 2042 2044 ... 2054 2056 2058]
  ...
  [2940 2942 2944 ... 2954 2956 2958]
  [2960 2962 2964 ... 2974 2976 2978]
  [2980 2982 2984 ... 2994 2996 2998]]

 [[3000 3002 3004 ... 3014 3016 3018]
  [3020 3022 3024 ... 3034 3036 3038]
  [3040 3042 3044 ... 3054 3056 3058]
  ...
  [3940 3942 3944 ... 3954 3956 3958]
  [3960 3962 3964 ... 3974 3976 3978]
  [3980 3982 3984 ... 3994 3996 3998]]

 ...

 [[6000 6002 6004 ... 6014 6016 6018]
  [6020 6022 6024 ... 6034 6036 6038]
  [6040 6042 6044 ... 6054 6056 6058]
  ...
  [6940 6942 6944 ... 6954 6956 6958]
  [6960 6962 6964 ... 6974 6976 6978]
  [6980 6982 6984 ... 6994 6996 6998]]

 [[7000 7002 7004 ... 7014 7016 7018]
  [7020 7022

Question 2b

In [86]:


selected_rows = reshaped_array_a[3, -3:, :]

#Calculate the mean along the columns (axis=1) to get a 1D array with 3 mean values
means = np.mean(selected_rows, axis=1)

#Printing mean value for last 3 rows in the 4th layer
print("Mean values for the last 3 rows in the 4th layer:")
print(means)

Mean values for the last 3 rows in the 4th layer:
[4949. 4969. 4989.]


Question 2c

In [88]:
import numpy as np

# Assuming you have already created and reshaped array_a as specified

# Extract the first 4 columns across all layers
first_4_columns_all_layers = reshaped_array_a[:, :, :4]

# Compute the product of all cells
result = np.prod(first_4_columns_all_layers)

# Print the result
print(result)


0


Question 2 (d)

In [89]:
import numpy as np

# Create array_b with evenly spaced values from 60 to 75
array_b = np.linspace(60, 75, 15)

# Create array_c with evenly spaced values from 8 to 10
array_c = np.linspace(8, 10, 15)

# Perform element-wise multiplication between array_b and array_c
result = array_b * array_c

# Print the result
print(result)


[480.         497.29591837 514.89795918 532.80612245 551.02040816
 569.54081633 588.36734694 607.5        626.93877551 646.68367347
 666.73469388 687.09183673 707.75510204 728.7244898  750.        ]


***Question 3***

In [90]:
def count_valid_emails(input_string):
    email_pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,7}\b'

    valid_emails = re.findall(email_pattern, input_string)

    # Filter the valid email addresses to remove those containing "@" more than once.
    valid_emails = [email for email in valid_emails if email.count('@') == 1]

    return len(valid_emails)


In [82]:
#Testing the to see whih emails are valid and which emails are invalid
text = "Contact us at user@server@domain.com or thapelo@gmail.com for more information."
count = count_valid_emails(text)
print(f"Number of valid email addresses found: {count}")


Number of valid email addresses found: 2
